name: Build Flet APK

on:
  workflow_dispatch:   # تقدر تشغل الـ build يدويًا من GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet buildozer cython

      - name: Install Android SDK & NDK
        uses: android-actions/setup-android@v3

      - name: Install Buildozer deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip zlib1g-dev \
            libncurses5-dev libstdc++6 libffi-dev libssl-dev autoconf automake \
            libtool pkg-config curl unzip openjdk-17-jdk

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet-app-apk
          path: bin/*.apk
