name: Android Build (Debug APK)

on:
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flet

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Accept Android SDK licenses
      run: yes | flutter doctor --android-licenses

    - name: Install Android SDK components
      run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Flet Build Debug APK
      run: |
        flutter config --no-analytics
        flet build apk --verbose --debug --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: List build outputs
      run: ls -R build

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-build-artifact
        path: build/flet/build/apk
        if-no-files-found: warn
        overwrite: false
